#!/usr/bin/env ruby
# coding: utf-8
#
# This script controls a pipeline of processes that convert the original
# CSV data into the se_open_data standard, one step at a time.
#
# We aim to put only logic specific to this project in this file, and
# keep it brief and clear. Shared logic should go into the {SeOpenData}
# library.
#
# This script can be invoked directly, or as part of the {SeOpenData}
# library's command-line API {SeOpenData::Cli}. For example, this
# just runs the conversion step (or specifically: a script in the
# current directory called `converter`):
#
#     seod convert 
#
# And this runs the complete chain of commands generating and
# deploying the linked data for this project, as configured by
# `settings/config.txt`:
#
#     seod run_all
#
# See the documentation on [`seod`]({SeOpenData::Cli}) for more
# information.

require_relative '../tools/se_open_data/lib/load_path'
require 'se_open_data/cli'

# Run the entry point if we're invoked as a script
# This just does the csv download
SeOpenData::Cli.command_http_download if __FILE__ == $0
