#!/bin/bash

SCRIPT=${BASH_SOURCE[0]}
REPO_DIR=$(readlink -f ${SCRIPT%/*}/../..)
SEOD=$REPO_DIR/tools/se_open_data/bin/seod

function process {
    local dir="${1:?directory argument required}"
    (
	cd $REPO_DIR/$dir &&
	    $SEOD limesurvey_export &&
	    $SEOD convert &&
	    $SEOD generate &&
	    sudo -nE $SEOD deploy &&
	    sudo -nE $SEOD create_w3id &&
	    sudo -nE $SEOD triplestore
    )
}

for dir in oxford newbridge; do
    echo "PROCESSING $dir..."
    process "$dir"
    echo
done

