#!/bin/bash

set -o pipefail
set -o errexit

# This script assumes seod v2.3.0 minimum

SCRIPT=${BASH_SOURCE[0]}
REPO_DIR=$(readlink -f ${SCRIPT%/*}/../..)

# Gems are only cached here if this exists, so make it
mkdir -p $REPO_DIR/caches/gems

# Reformat the output of a command to make it easier to follow in logs
function logify() {
    local dir=$1
    shift
    printf "\n[For $dir: $*]\n"
    # Prefix STDOUT with space, but STDERR with an exclamation too
    # Piping to cat makes this function wait for the process substitutions before returning
    "$@" > >(sed -e 's/^/  /') 2> >(sed -e 's/^/  ! /') | cat
}

# Process one directory (passed as first argument)
#
# This should return a non-zero code if any part fails but the other
# dirs should still be processed (or possibly exit, in the extreme
# case when all processing should stop)
function process {
    local dir="${1:?directory argument required}"
    (
        cd $REPO_DIR/$dir &&
        logify $dir bundle install --quiet &&
        logify $dir bundle exec seod run_all
    )
}

FAILS=()
set +o errexit # <- we want to manage failure more finely than this here

for dir in owned-by-oxford newbridge mersey-green deep-adaptation dotcoop workers-coop; do
    echo "PROCESSING $dir..."
    
    process $dir
    case "$?" in
        0)
            echo "SUCCEEDED $dir"
            ;;
        100)
            echo "NO CHANGES $dir (return code $?)"
            ;;
        *)
            echo "FAILED $dir (return code $?)"
            FAILS+=($dir)
            ;;
    esac
done

echo "FINISHING with ${#FAILS[@]} failed: ${FAILS[@]}"
exit ${#FAILS[@]}
