#!/usr/bin/env ruby
# coding: utf-8
require_relative '../tools/se_open_data/lib/load_path'
require 'se_open_data/csv/converter/limesurveycore'

# Find the config file...
config = SeOpenData::Config.load

# Google sheets can't export with a semi-colon delimiter
config.store(:ORIGINAL_CSV_COL_SEP, ',');

# Run the entry point if we're invoked as a script
# This just does the csv conversion.
SeOpenData::CSV::Converter::LimeSurveyCore.convert(config) if __FILE__ == $0

