source "https://rubygems.org"
gem "se_open_data", :github => "DigitalCommons/se-open-data", :tag => "v2.3.0"
gem "rdf-rdfxml", "~> 3.2", ">= 3.2.1"
gem "stringio", "< 3.1.0" # Workaround for a 3.1.0 issue

# The workaround is for a problem similar to this, i.e. RubyGems indexing problems:
# https://github.com/rubygems/rubygems.org/issues/4247
# Hopefully it will resolve itself upstream.
